name: Bruno Paulin
url: http://bpaulin.net
description: 'Aide mémoire en libre service'
pygments: true
paginate: 5
paginate_path: "page:num"
exclude: [README, LICENSE, .gitignore, bpaulin.net.sublime-project, bpaulin.net.sublime-workspace]