links:
  github: https://github.com/bpaulin
  linkedin: https://www.linkedin.com/in/bruno-paulin-29904a67
permalink: /articles/:categories/:year/:month/:day/:title/
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
exclude:
  - README
  - LICENSE
  - .gitignore
  - vendor
theme: minima
title: Bpaulin.net
author: Bruno Paulin
description: 'Aide mémoire en libre service'
github_username: bpaulin
# linkedin_username: bruno-paulin-29904a67
google_analytics: UA-46867580-1
# header_pages:
#   - about.md
#   - projects.md
