name: Bruno Paulin
navigation:
    articles:
        url: /articles/
        text: Articles
        icon: fa-pencil-square-o
    projets:
        url: /projets/
        text: Projets
        icon: fa-github-alt
    apropos:
        url: /apropos/
        text: A propos
        icon: fa-question-circle
url: http://bpaulin.net
description: 'Aide mémoire en libre service'
pygments: true
exclude: 
    - Gruntfile.js
    - validation.report.json
    - validation.status.json
    - json
    - README
    - LICENSE
    - .gitignore
    - bpaulin.net.sublime-project
    - bpaulin.net.sublime-workspace
    - mel.sh
    - node_modules
markdown: kramdown
kramdown:
  auto_ids: false
permalink: /articles/:categories/:year/:month/:day/:title/